{
  "name": "financial_model",
  "compatibilityLevel": 1604,
  "model": {
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "tables": [
      {
        "name": "daily_summary",
        "description": "Gold layer daily aggregated financial data with moving averages and return metrics",
        "dataCategory": "Time",
        "columns": [
          {"name": "Symbol",                  "dataType": "string",  "sourceColumn": "Symbol"},
          {"name": "Date",                    "dataType": "dateTime","sourceColumn": "Date",    "formatString": "Short Date", "isKey": true},
          {"name": "Open",                    "dataType": "double",  "sourceColumn": "open"},
          {"name": "High",                    "dataType": "double",  "sourceColumn": "high"},
          {"name": "Low",                     "dataType": "double",  "sourceColumn": "low"},
          {"name": "Close",                   "dataType": "double",  "sourceColumn": "close"},
          {"name": "Total Volume",            "dataType": "int64",   "sourceColumn": "total_volume"},
          {"name": "Daily Return %",          "dataType": "double",  "sourceColumn": "daily_return_pct",         "formatString": "0.00%"},
          {"name": "MA Close 7D",             "dataType": "double",  "sourceColumn": "ma_close_7d"},
          {"name": "MA Close 30D",            "dataType": "double",  "sourceColumn": "ma_close_30d"},
          {"name": "Day over Day Return %",   "dataType": "double",  "sourceColumn": "day_over_day_return_pct",  "formatString": "0.00%"},
          {"name": "Cumulative Return %",     "dataType": "double",  "sourceColumn": "cumulative_return_pct",    "formatString": "0.00%"}
        ],
        "measures": [
          {
            "name": "Latest Close",
            "expression": "LASTNONBLANK(daily_summary[Close], 1)",
            "formatString": "$ #,0.00",
            "description": "Most recent closing price for selected symbol"
          },
          {
            "name": "Avg Daily Return %",
            "expression": "AVERAGE(daily_summary[Daily Return %])",
            "formatString": "0.00%",
            "description": "Average daily return over selected period"
          },
          {
            "name": "Total Volume (M)",
            "expression": "DIVIDE(SUM(daily_summary[Total Volume]), 1000000)",
            "formatString": "#,0.0",
            "description": "Total traded volume in millions"
          },
          {
            "name": "All-Time High",
            "expression": "MAX(daily_summary[High])",
            "formatString": "$ #,0.00"
          },
          {
            "name": "All-Time Low",
            "expression": "MIN(daily_summary[Low])",
            "formatString": "$ #,0.00"
          },
          {
            "name": "Price Range",
            "expression": "DIVIDE([All-Time High] - [All-Time Low], [All-Time Low], BLANK())",
            "formatString": "0.00%",
            "description": "Intraday price range as % of All-Time Low"
          },
          {
            "name": "Trend Signal",
            "expression": "IF([MA Close 7D] > [MA Close 30D], \"BULLISH\", IF([MA Close 7D] < [MA Close 30D], \"BEARISH\", \"NEUTRAL\"))",
            "description": "Golden/death cross signal based on MA7 vs MA30",
            "dataType": "string"
          },
          {
            "name": "MA Close 7D",
            "expression": "AVERAGE(daily_summary[MA Close 7D])",
            "formatString": "$ #,0.00"
          },
          {
            "name": "MA Close 30D",
            "expression": "AVERAGE(daily_summary[MA Close 30D])",
            "formatString": "$ #,0.00"
          }
        ],
        "partitions": [
          {
            "name": "daily_summary",
            "mode": "directQuery",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"synw-financial-data-ondemand.sql.azuresynapse.net\", \"financial_analytics\"),",
                "    gold_daily_summary = Source{[Schema=\"gold\", Item=\"daily_summary\"]}[Data]",
                "in",
                "    gold_daily_summary"
              ]
            }
          }
        ]
      },
      {
        "name": "Date",
        "description": "Date dimension table",
        "isDateTable": true,
        "columns": [
          {"name": "Date",        "dataType": "dateTime", "isKey": true, "formatString": "Short Date"},
          {"name": "Year",        "dataType": "int64"},
          {"name": "Quarter",     "dataType": "int64"},
          {"name": "Month",       "dataType": "int64"},
          {"name": "Month Name",  "dataType": "string"},
          {"name": "Week",        "dataType": "int64"},
          {"name": "Day of Week", "dataType": "string"}
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    StartDate = #date(2020, 1, 1),",
                "    EndDate   = Date.From(DateTime.LocalNow()),",
                "    DateList  = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),",
                "    Source    = Table.FromList(DateList, Splitter.SplitByNothing(), {\"Date\"}),",
                "    Typed     = Table.TransformColumnTypes(Source, {{\"Date\", type date}}),",
                "    AddYear   = Table.AddColumn(Typed, \"Year\",       each Date.Year([Date]),         Int64.Type),",
                "    AddQ      = Table.AddColumn(AddYear, \"Quarter\",  each Date.QuarterOfYear([Date]),Int64.Type),",
                "    AddMonth  = Table.AddColumn(AddQ, \"Month\",       each Date.Month([Date]),        Int64.Type),",
                "    AddMName  = Table.AddColumn(AddMonth, \"Month Name\", each Date.MonthName([Date]), type text),",
                "    AddWeek   = Table.AddColumn(AddMName, \"Week\",    each Date.WeekOfYear([Date]),   Int64.Type),",
                "    AddDOW    = Table.AddColumn(AddWeek, \"Day of Week\", each Date.DayOfWeekName([Date]), type text)",
                "in",
                "    AddDOW"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "daily_summary_Date",
        "fromTable": "daily_summary",
        "fromColumn": "Date",
        "toTable": "Date",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "version": "1.0.0"
        }
      }
    ]
  }
}
